steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
      ]
    dir: "noteapp-fe"
timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
